### PR TITLE
enable PerlModules that provide multiple modules

### PR DESCRIPTION
**Pull request by lexming**
Suggestion for your PR https://github.com/easybuilders/easybuild-easyblocks/pull/2386

### CODE REVIEW

**Comment by Flamefire** [comment]
In the PR you said e.g. IO:* is part of perl base. How would those be handled with this change?

I wouldn't mind combining both, i.e. allowing string-only items and multiple module names.

However I remember ECs being type-checked. Would this "abuse" of modulename throw this off? @boegel?

**Comment by boegel** [comment]
It would be better to implement support for `modulename` being a list of values in EasyBuild framework.

This is hacky at best, since it also does the rest of the sanity check, not just the "import" check...

**Comment by lexming** [comment]
I targeted the easyblock of PerlModule because this might only be necessary with Perl. I'm not aware of any group of packages in R or Python being distributed in a single source tarball. So the goal is just to emulate _single-module_ virtual extensions and use existing facilities in framework.

If you prefer to have general support for lists in `modulename`, them that's another story. I'll take a look in framework to see how much work is needed to get that done.

**Comment by lexming** [comment]
Abandoned. Code will stay available at https://github.com/lexming/easybuild-easyblocks/tree/multi_perlmod

**Pull request closed without merging**
